language: python
python:
  - "3.6"
install:
  - pip install PyQt5
  - pip install pytest pytest-pep8 coverage pylint coveralls
  - pip install radon xenon
script:
  - PYTHONPATH=. pytest
  - PYTHONPATH=. pytest --pep8
  - PYTHONPATH=. pylint *.py
  - PYTHONPATH=. pylint */*.py
  - PYTHONPATH=. pylint */*/*.py
  - PYTHONPATH=. coverage run --source=. -m unittest discover -s test/
  - PYTHONPATH=. coverage report -m
  - PYTHONPATH=. radon cc *.py */*.py */*/*.py */*/*/*.py
  - PYTHONPATH=. xenon itasks --max-absolute A --max-modules A --max-average A
after_success:
  - coveralls
notifications:
  email: false